name: Deploy Website

on:
  push:
    branches: [ "source" ]

jobs:
  deploy-website:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: Sync Engine Module
      run: |
        git submodule sync
        git submodule update --init
    - name: Deploying to GitHub Pages
      env:
        GIT_USER: DevPlatBot
        CURRENT_BRANCH: source
        GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "devplatformbots@overwolf.com"
        git config --global user.name "DevPlatBot"
        yarn install --immutable && yarn deploy
